// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Roles
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOpt_fieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "base_role_type")]
        #pragma warning disable CS1591
        Base_role_type,
        #pragma warning restore CS1591
        [EnumMember(Value = "creation_time")]
        #pragma warning disable CS1591
        Creation_time,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_standard_role")]
        #pragma warning disable CS1591
        Is_standard_role,
        #pragma warning restore CS1591
        [EnumMember(Value = "modified_at")]
        #pragma warning disable CS1591
        Modified_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "offset")]
        #pragma warning disable CS1591
        Offset,
        #pragma warning restore CS1591
        [EnumMember(Value = "path")]
        #pragma warning disable CS1591
        Path,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions")]
        #pragma warning disable CS1591
        Permissions,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.allowed_guest_invites")]
        #pragma warning disable CS1591
        PermissionsAllowed_guest_invites,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.assign_roles")]
        #pragma warning disable CS1591
        PermissionsAssign_roles,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.create_and_edit_ai_automations")]
        #pragma warning disable CS1591
        PermissionsCreate_and_edit_ai_automations,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.create_app_authorization")]
        #pragma warning disable CS1591
        PermissionsCreate_app_authorization,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.create_global_custom_fields")]
        #pragma warning disable CS1591
        PermissionsCreate_global_custom_fields,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.create_pat_authorization")]
        #pragma warning disable CS1591
        PermissionsCreate_pat_authorization,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.create_team")]
        #pragma warning disable CS1591
        PermissionsCreate_team,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.download_mobile_attachments")]
        #pragma warning disable CS1591
        PermissionsDownload_mobile_attachments,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.export_project_data")]
        #pragma warning disable CS1591
        PermissionsExport_project_data,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.import_data")]
        #pragma warning disable CS1591
        PermissionsImport_data,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.manage_roles")]
        #pragma warning disable CS1591
        PermissionsManage_roles,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.proactive_ai")]
        #pragma warning disable CS1591
        PermissionsProactive_ai,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.share_goal_with_domain")]
        #pragma warning disable CS1591
        PermissionsShare_goal_with_domain,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.share_portfolios_with_org")]
        #pragma warning disable CS1591
        PermissionsShare_portfolios_with_org,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.standard_ai")]
        #pragma warning disable CS1591
        PermissionsStandard_ai,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.task_deletion_policy")]
        #pragma warning disable CS1591
        PermissionsTask_deletion_policy,
        #pragma warning restore CS1591
        [EnumMember(Value = "permissions.upload_attachments")]
        #pragma warning disable CS1591
        PermissionsUpload_attachments,
        #pragma warning restore CS1591
        [EnumMember(Value = "uri")]
        #pragma warning disable CS1591
        Uri,
        #pragma warning restore CS1591
        [EnumMember(Value = "workspace")]
        #pragma warning disable CS1591
        Workspace,
        #pragma warning restore CS1591
        [EnumMember(Value = "workspace.name")]
        #pragma warning disable CS1591
        WorkspaceName,
        #pragma warning restore CS1591
    }
}
