// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Goals.Item.AddSupportingRelationship
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostOpt_fieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "contribution_weight")]
        #pragma warning disable CS1591
        Contribution_weight,
        #pragma warning restore CS1591
        [EnumMember(Value = "resource_subtype")]
        #pragma warning disable CS1591
        Resource_subtype,
        #pragma warning restore CS1591
        [EnumMember(Value = "supported_goal")]
        #pragma warning disable CS1591
        Supported_goal,
        #pragma warning restore CS1591
        [EnumMember(Value = "supported_goal.name")]
        #pragma warning disable CS1591
        Supported_goalName,
        #pragma warning restore CS1591
        [EnumMember(Value = "supported_goal.owner")]
        #pragma warning disable CS1591
        Supported_goalOwner,
        #pragma warning restore CS1591
        [EnumMember(Value = "supported_goal.owner.name")]
        #pragma warning disable CS1591
        Supported_goalOwnerName,
        #pragma warning restore CS1591
        [EnumMember(Value = "supporting_resource")]
        #pragma warning disable CS1591
        Supporting_resource,
        #pragma warning restore CS1591
        [EnumMember(Value = "supporting_resource.name")]
        #pragma warning disable CS1591
        Supporting_resourceName,
        #pragma warning restore CS1591
    }
}
