// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddCustomFieldSettingRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The custom_field property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest.AddCustomFieldSettingRequest_custom_field? CustomField { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest.AddCustomFieldSettingRequest_custom_field CustomField { get; set; }
#endif
        /// <summary>A gid of a Custom Field Setting on this container, after which the new Custom Field Setting will be added.  `insert_before` and `insert_after` parameters cannot both be specified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InsertAfter { get; set; }
#nullable restore
#else
        public string InsertAfter { get; set; }
#endif
        /// <summary>A gid of a Custom Field Setting on this container, before which the new Custom Field Setting will be added.  `insert_before` and `insert_after` parameters cannot both be specified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InsertBefore { get; set; }
#nullable restore
#else
        public string InsertBefore { get; set; }
#endif
        /// <summary>Whether this field should be considered important to this container (for instance, to display in the list view of items in the container).</summary>
        public bool? IsImportant { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest"/> and sets the default values.
        /// </summary>
        public AddCustomFieldSettingRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_field", n => { CustomField = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest.AddCustomFieldSettingRequest_custom_field>(global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest.AddCustomFieldSettingRequest_custom_field.CreateFromDiscriminatorValue); } },
                { "insert_after", n => { InsertAfter = n.GetStringValue(); } },
                { "insert_before", n => { InsertBefore = n.GetStringValue(); } },
                { "is_important", n => { IsImportant = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest.AddCustomFieldSettingRequest_custom_field>("custom_field", CustomField);
            writer.WriteStringValue("insert_after", InsertAfter);
            writer.WriteStringValue("insert_before", InsertBefore);
            writer.WriteBoolValue("is_important", IsImportant);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest_custom_fieldMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AddCustomFieldSettingRequest_custom_field : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest_custom_fieldMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest_custom_fieldMember1? AddCustomFieldSettingRequestCustomFieldMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest_custom_fieldMember1 AddCustomFieldSettingRequestCustomFieldMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest.AddCustomFieldSettingRequest_custom_field"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest.AddCustomFieldSettingRequest_custom_field CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest.AddCustomFieldSettingRequest_custom_field();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AddCustomFieldSettingRequestCustomFieldMember1 = new global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest_custom_fieldMember1();
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AddCustomFieldSettingRequestCustomFieldMember1 != null)
                {
                    return AddCustomFieldSettingRequestCustomFieldMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(AddCustomFieldSettingRequestCustomFieldMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.AddCustomFieldSettingRequest_custom_fieldMember1>(null, AddCustomFieldSettingRequestCustomFieldMember1);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
