// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>Whether the credits were drawn from a paid or free balance.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AiStudioRunResponseCreditSource
    {
        [EnumMember(Value = "paid")]
        #pragma warning disable CS1591
        Paid,
        #pragma warning restore CS1591
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
    }
}
