// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>The type of context.Can be one of `web`, `desktop`, `mobile`, `asana_support`, `asana`, `email`, or `api`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuditLogEvent_context_context_type
    {
        [EnumMember(Value = "web")]
        #pragma warning disable CS1591
        Web,
        #pragma warning restore CS1591
        [EnumMember(Value = "desktop")]
        #pragma warning disable CS1591
        Desktop,
        #pragma warning restore CS1591
        [EnumMember(Value = "mobile")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "asana_support")]
        #pragma warning disable CS1591
        Asana_support,
        #pragma warning restore CS1591
        [EnumMember(Value = "asana")]
        #pragma warning disable CS1591
        Asana,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "api")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
    }
}
