// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>
    /// An action object for use in a batch request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BatchRequest_actions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>For `GET` requests, this should be a map of query parameters you would have normally passed in the URL. Options and pagination are not accepted here; put them in `options` instead. For `POST`, `PATCH`, and `PUT` methods, this should be the content you would have normally put in the data field of the body.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_data? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_data Data { get; set; }
#endif
        /// <summary>The HTTP method you wish to emulate for the action.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_method? Method { get; set; }
        /// <summary>Pagination (`limit` and `offset`) and output options (`fields` or `expand`) for the action. “Pretty” JSON output is not an available option on individual actions; if you want pretty output, specify that option on the parent request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_options? Options { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_options Options { get; set; }
#endif
        /// <summary>The path of the desired endpoint relative to the API’s base URL. Query parameters are not accepted here; put them in `data` instead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RelativePath { get; set; }
#nullable restore
#else
        public string RelativePath { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions"/> and sets the default values.
        /// </summary>
        public BatchRequest_actions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_data>(global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_data.CreateFromDiscriminatorValue); } },
                { "method", n => { Method = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_method>(); } },
                { "options", n => { Options = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_options>(global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_options.CreateFromDiscriminatorValue); } },
                { "relative_path", n => { RelativePath = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_data>("data", Data);
            writer.WriteEnumValue<global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_method>("method", Method);
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.BatchRequest_actions_options>("options", Options);
            writer.WriteStringValue("relative_path", RelativePath);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
