// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>
    /// A response object returned from a batch request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BatchResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The JSON body that the invoked endpoint returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.BatchResponse_body? Body { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.BatchResponse_body Body { get; set; }
#endif
        /// <summary>A map of HTTP headers specific to this result. This is primarily used for returning a `Location` header to accompany a `201 Created` result.  The parent HTTP response will contain all common headers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.BatchResponse_headers? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.BatchResponse_headers Headers { get; set; }
#endif
        /// <summary>The HTTP status code that the invoked endpoint returned.</summary>
        public int? StatusCode { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Models.BatchResponse"/> and sets the default values.
        /// </summary>
        public BatchResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.BatchResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Asana.OpenApiClient.Models.BatchResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Asana.OpenApiClient.Models.BatchResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.BatchResponse_body>(global::Soenneker.Asana.OpenApiClient.Models.BatchResponse_body.CreateFromDiscriminatorValue); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.BatchResponse_headers>(global::Soenneker.Asana.OpenApiClient.Models.BatchResponse_headers.CreateFromDiscriminatorValue); } },
                { "status_code", n => { StatusCode = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.BatchResponse_body>("body", Body);
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.BatchResponse_headers>("headers", Headers);
            writer.WriteIntValue("status_code", StatusCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
