// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>&quot;The data source for the estimate. `tasks`: use task-level estimated time attributed to the parent. `capacity_plans`: use capacity plan estimates attributed to the parent. `none`: disables the estimate; only valid when `enabled` is `false`. When `enabled` is `true`, `source` must not be `none`.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BudgetResponseEstimateSource
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "tasks")]
        #pragma warning disable CS1591
        Tasks,
        #pragma warning restore CS1591
        [EnumMember(Value = "capacity_plans")]
        #pragma warning disable CS1591
        CapacityPlans,
        #pragma warning restore CS1591
    }
}
