// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>Billable status filter applied to time tracking entries contributing to the actual value. Determines which entries are included in aggregation. When not provided, defaults to `billable`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BudgetRequest_actual_billable_status_filter
    {
        [EnumMember(Value = "billable")]
        #pragma warning disable CS1591
        Billable,
        #pragma warning restore CS1591
        [EnumMember(Value = "non_billable")]
        #pragma warning disable CS1591
        Non_billable,
        #pragma warning restore CS1591
        [EnumMember(Value = "any")]
        #pragma warning disable CS1591
        Any,
        #pragma warning restore CS1591
    }
}
