// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>*Conditional*. A unique identifier to associate this field with the template source of truth.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomFieldRequestAsanaCreatedField
    {
        [EnumMember(Value = "a_v_requirements")]
        #pragma warning disable CS1591
        AVRequirements,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_name")]
        #pragma warning disable CS1591
        AccountName,
        #pragma warning restore CS1591
        [EnumMember(Value = "actionable")]
        #pragma warning disable CS1591
        Actionable,
        #pragma warning restore CS1591
        [EnumMember(Value = "align_shipping_link")]
        #pragma warning disable CS1591
        AlignShippingLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "align_status")]
        #pragma warning disable CS1591
        AlignStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "allotted_time")]
        #pragma warning disable CS1591
        AllottedTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "appointment")]
        #pragma warning disable CS1591
        Appointment,
        #pragma warning restore CS1591
        [EnumMember(Value = "approval_stage")]
        #pragma warning disable CS1591
        ApprovalStage,
        #pragma warning restore CS1591
        [EnumMember(Value = "approved")]
        #pragma warning disable CS1591
        Approved,
        #pragma warning restore CS1591
        [EnumMember(Value = "article_series")]
        #pragma warning disable CS1591
        ArticleSeries,
        #pragma warning restore CS1591
        [EnumMember(Value = "board_committee")]
        #pragma warning disable CS1591
        BoardCommittee,
        #pragma warning restore CS1591
        [EnumMember(Value = "browser")]
        #pragma warning disable CS1591
        Browser,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign_audience")]
        #pragma warning disable CS1591
        CampaignAudience,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign_project_status")]
        #pragma warning disable CS1591
        CampaignProjectStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign_regions")]
        #pragma warning disable CS1591
        CampaignRegions,
        #pragma warning restore CS1591
        [EnumMember(Value = "channel_primary")]
        #pragma warning disable CS1591
        ChannelPrimary,
        #pragma warning restore CS1591
        [EnumMember(Value = "client_topic_type")]
        #pragma warning disable CS1591
        ClientTopicType,
        #pragma warning restore CS1591
        [EnumMember(Value = "complete_by")]
        #pragma warning disable CS1591
        CompleteBy,
        #pragma warning restore CS1591
        [EnumMember(Value = "contact")]
        #pragma warning disable CS1591
        Contact,
        #pragma warning restore CS1591
        [EnumMember(Value = "contact_email_address")]
        #pragma warning disable CS1591
        ContactEmailAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "content_channels")]
        #pragma warning disable CS1591
        ContentChannels,
        #pragma warning restore CS1591
        [EnumMember(Value = "content_channels_needed")]
        #pragma warning disable CS1591
        ContentChannelsNeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "content_stage")]
        #pragma warning disable CS1591
        ContentStage,
        #pragma warning restore CS1591
        [EnumMember(Value = "content_type")]
        #pragma warning disable CS1591
        ContentType,
        #pragma warning restore CS1591
        [EnumMember(Value = "contract")]
        #pragma warning disable CS1591
        Contract,
        #pragma warning restore CS1591
        [EnumMember(Value = "contract_status")]
        #pragma warning disable CS1591
        ContractStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "cost")]
        #pragma warning disable CS1591
        Cost,
        #pragma warning restore CS1591
        [EnumMember(Value = "creation_stage")]
        #pragma warning disable CS1591
        CreationStage,
        #pragma warning restore CS1591
        [EnumMember(Value = "creative_channel")]
        #pragma warning disable CS1591
        CreativeChannel,
        #pragma warning restore CS1591
        [EnumMember(Value = "creative_needed")]
        #pragma warning disable CS1591
        CreativeNeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "creative_needs")]
        #pragma warning disable CS1591
        CreativeNeeds,
        #pragma warning restore CS1591
        [EnumMember(Value = "data_sensitivity")]
        #pragma warning disable CS1591
        DataSensitivity,
        #pragma warning restore CS1591
        [EnumMember(Value = "deal_size")]
        #pragma warning disable CS1591
        DealSize,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivery_appt")]
        #pragma warning disable CS1591
        DeliveryAppt,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivery_appt_date")]
        #pragma warning disable CS1591
        DeliveryApptDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "department")]
        #pragma warning disable CS1591
        Department,
        #pragma warning restore CS1591
        [EnumMember(Value = "department_responsible")]
        #pragma warning disable CS1591
        DepartmentResponsible,
        #pragma warning restore CS1591
        [EnumMember(Value = "design_request_needed")]
        #pragma warning disable CS1591
        DesignRequestNeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "design_request_type")]
        #pragma warning disable CS1591
        DesignRequestType,
        #pragma warning restore CS1591
        [EnumMember(Value = "discussion_category")]
        #pragma warning disable CS1591
        DiscussionCategory,
        #pragma warning restore CS1591
        [EnumMember(Value = "do_this_task")]
        #pragma warning disable CS1591
        DoThisTask,
        #pragma warning restore CS1591
        [EnumMember(Value = "editorial_content_status")]
        #pragma warning disable CS1591
        EditorialContentStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "editorial_content_tag")]
        #pragma warning disable CS1591
        EditorialContentTag,
        #pragma warning restore CS1591
        [EnumMember(Value = "editorial_content_type")]
        #pragma warning disable CS1591
        EditorialContentType,
        #pragma warning restore CS1591
        [EnumMember(Value = "effort")]
        #pragma warning disable CS1591
        Effort,
        #pragma warning restore CS1591
        [EnumMember(Value = "effort_level")]
        #pragma warning disable CS1591
        EffortLevel,
        #pragma warning restore CS1591
        [EnumMember(Value = "est_completion_date")]
        #pragma warning disable CS1591
        EstCompletionDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "estimated_time")]
        #pragma warning disable CS1591
        EstimatedTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "estimated_value")]
        #pragma warning disable CS1591
        EstimatedValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "expected_cost")]
        #pragma warning disable CS1591
        ExpectedCost,
        #pragma warning restore CS1591
        [EnumMember(Value = "external_steps_needed")]
        #pragma warning disable CS1591
        ExternalStepsNeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "favorite_idea")]
        #pragma warning disable CS1591
        FavoriteIdea,
        #pragma warning restore CS1591
        [EnumMember(Value = "feedback_type")]
        #pragma warning disable CS1591
        FeedbackType,
        #pragma warning restore CS1591
        [EnumMember(Value = "financial")]
        #pragma warning disable CS1591
        Financial,
        #pragma warning restore CS1591
        [EnumMember(Value = "funding_amount")]
        #pragma warning disable CS1591
        FundingAmount,
        #pragma warning restore CS1591
        [EnumMember(Value = "grant_application_process")]
        #pragma warning disable CS1591
        GrantApplicationProcess,
        #pragma warning restore CS1591
        [EnumMember(Value = "hiring_candidate_status")]
        #pragma warning disable CS1591
        HiringCandidateStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "idea_status")]
        #pragma warning disable CS1591
        IdeaStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "ids_link")]
        #pragma warning disable CS1591
        IdsLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "ids_patient_link")]
        #pragma warning disable CS1591
        IdsPatientLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "implementation_stage")]
        #pragma warning disable CS1591
        ImplementationStage,
        #pragma warning restore CS1591
        [EnumMember(Value = "insurance")]
        #pragma warning disable CS1591
        Insurance,
        #pragma warning restore CS1591
        [EnumMember(Value = "interview_area")]
        #pragma warning disable CS1591
        InterviewArea,
        #pragma warning restore CS1591
        [EnumMember(Value = "interview_question_score")]
        #pragma warning disable CS1591
        InterviewQuestionScore,
        #pragma warning restore CS1591
        [EnumMember(Value = "itero_scan_link")]
        #pragma warning disable CS1591
        IteroScanLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "job_s_applied_to")]
        #pragma warning disable CS1591
        JobSAppliedTo,
        #pragma warning restore CS1591
        [EnumMember(Value = "lab")]
        #pragma warning disable CS1591
        Lab,
        #pragma warning restore CS1591
        [EnumMember(Value = "launch_status")]
        #pragma warning disable CS1591
        LaunchStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "lead_status")]
        #pragma warning disable CS1591
        LeadStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "localization_language")]
        #pragma warning disable CS1591
        LocalizationLanguage,
        #pragma warning restore CS1591
        [EnumMember(Value = "localization_market_team")]
        #pragma warning disable CS1591
        LocalizationMarketTeam,
        #pragma warning restore CS1591
        [EnumMember(Value = "localization_status")]
        #pragma warning disable CS1591
        LocalizationStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "meeting_minutes")]
        #pragma warning disable CS1591
        MeetingMinutes,
        #pragma warning restore CS1591
        [EnumMember(Value = "meeting_needed")]
        #pragma warning disable CS1591
        MeetingNeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "minutes")]
        #pragma warning disable CS1591
        Minutes,
        #pragma warning restore CS1591
        [EnumMember(Value = "mrr")]
        #pragma warning disable CS1591
        Mrr,
        #pragma warning restore CS1591
        [EnumMember(Value = "must_localize")]
        #pragma warning disable CS1591
        MustLocalize,
        #pragma warning restore CS1591
        [EnumMember(Value = "name_of_foundation")]
        #pragma warning disable CS1591
        NameOfFoundation,
        #pragma warning restore CS1591
        [EnumMember(Value = "need_to_follow_up")]
        #pragma warning disable CS1591
        NeedToFollowUp,
        #pragma warning restore CS1591
        [EnumMember(Value = "next_appointment")]
        #pragma warning disable CS1591
        NextAppointment,
        #pragma warning restore CS1591
        [EnumMember(Value = "next_steps_sales")]
        #pragma warning disable CS1591
        NextStepsSales,
        #pragma warning restore CS1591
        [EnumMember(Value = "num_people")]
        #pragma warning disable CS1591
        NumPeople,
        #pragma warning restore CS1591
        [EnumMember(Value = "number_of_user_reports")]
        #pragma warning disable CS1591
        NumberOfUserReports,
        #pragma warning restore CS1591
        [EnumMember(Value = "office_location")]
        #pragma warning disable CS1591
        OfficeLocation,
        #pragma warning restore CS1591
        [EnumMember(Value = "onboarding_activity")]
        #pragma warning disable CS1591
        OnboardingActivity,
        #pragma warning restore CS1591
        [EnumMember(Value = "owner")]
        #pragma warning disable CS1591
        Owner,
        #pragma warning restore CS1591
        [EnumMember(Value = "participants_needed")]
        #pragma warning disable CS1591
        ParticipantsNeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "patient_date_of_birth")]
        #pragma warning disable CS1591
        PatientDateOfBirth,
        #pragma warning restore CS1591
        [EnumMember(Value = "patient_email")]
        #pragma warning disable CS1591
        PatientEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "patient_phone")]
        #pragma warning disable CS1591
        PatientPhone,
        #pragma warning restore CS1591
        [EnumMember(Value = "patient_status")]
        #pragma warning disable CS1591
        PatientStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone_number")]
        #pragma warning disable CS1591
        PhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "planning_category")]
        #pragma warning disable CS1591
        PlanningCategory,
        #pragma warning restore CS1591
        [EnumMember(Value = "point_of_contact")]
        #pragma warning disable CS1591
        PointOfContact,
        #pragma warning restore CS1591
        [EnumMember(Value = "position")]
        #pragma warning disable CS1591
        Position,
        #pragma warning restore CS1591
        [EnumMember(Value = "post_format")]
        #pragma warning disable CS1591
        PostFormat,
        #pragma warning restore CS1591
        [EnumMember(Value = "prescription")]
        #pragma warning disable CS1591
        Prescription,
        #pragma warning restore CS1591
        [EnumMember(Value = "priority")]
        #pragma warning disable CS1591
        Priority,
        #pragma warning restore CS1591
        [EnumMember(Value = "priority_level")]
        #pragma warning disable CS1591
        PriorityLevel,
        #pragma warning restore CS1591
        [EnumMember(Value = "product")]
        #pragma warning disable CS1591
        Product,
        #pragma warning restore CS1591
        [EnumMember(Value = "product_stage")]
        #pragma warning disable CS1591
        ProductStage,
        #pragma warning restore CS1591
        [EnumMember(Value = "progress")]
        #pragma warning disable CS1591
        Progress,
        #pragma warning restore CS1591
        [EnumMember(Value = "project_size")]
        #pragma warning disable CS1591
        ProjectSize,
        #pragma warning restore CS1591
        [EnumMember(Value = "project_status")]
        #pragma warning disable CS1591
        ProjectStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "proposed_budget")]
        #pragma warning disable CS1591
        ProposedBudget,
        #pragma warning restore CS1591
        [EnumMember(Value = "publish_status")]
        #pragma warning disable CS1591
        PublishStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "reason_for_scan")]
        #pragma warning disable CS1591
        ReasonForScan,
        #pragma warning restore CS1591
        [EnumMember(Value = "referral")]
        #pragma warning disable CS1591
        Referral,
        #pragma warning restore CS1591
        [EnumMember(Value = "request_type")]
        #pragma warning disable CS1591
        RequestType,
        #pragma warning restore CS1591
        [EnumMember(Value = "research_status")]
        #pragma warning disable CS1591
        ResearchStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "responsible_department")]
        #pragma warning disable CS1591
        ResponsibleDepartment,
        #pragma warning restore CS1591
        [EnumMember(Value = "responsible_team")]
        #pragma warning disable CS1591
        ResponsibleTeam,
        #pragma warning restore CS1591
        [EnumMember(Value = "risk_assessment_status")]
        #pragma warning disable CS1591
        RiskAssessmentStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "room_name")]
        #pragma warning disable CS1591
        RoomName,
        #pragma warning restore CS1591
        [EnumMember(Value = "sales_counterpart")]
        #pragma warning disable CS1591
        SalesCounterpart,
        #pragma warning restore CS1591
        [EnumMember(Value = "sentiment")]
        #pragma warning disable CS1591
        Sentiment,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_link")]
        #pragma warning disable CS1591
        ShippingLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "social_channels")]
        #pragma warning disable CS1591
        SocialChannels,
        #pragma warning restore CS1591
        [EnumMember(Value = "stage")]
        #pragma warning disable CS1591
        Stage,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "status_design")]
        #pragma warning disable CS1591
        StatusDesign,
        #pragma warning restore CS1591
        [EnumMember(Value = "status_of_initiative")]
        #pragma warning disable CS1591
        StatusOfInitiative,
        #pragma warning restore CS1591
        [EnumMember(Value = "system_setup")]
        #pragma warning disable CS1591
        SystemSetup,
        #pragma warning restore CS1591
        [EnumMember(Value = "task_progress")]
        #pragma warning disable CS1591
        TaskProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "team")]
        #pragma warning disable CS1591
        Team,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_marketing")]
        #pragma warning disable CS1591
        TeamMarketing,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_responsible")]
        #pragma warning disable CS1591
        TeamResponsible,
        #pragma warning restore CS1591
        [EnumMember(Value = "time_it_takes_to_complete_tasks")]
        #pragma warning disable CS1591
        TimeItTakesToCompleteTasks,
        #pragma warning restore CS1591
        [EnumMember(Value = "timeframe")]
        #pragma warning disable CS1591
        Timeframe,
        #pragma warning restore CS1591
        [EnumMember(Value = "treatment_type")]
        #pragma warning disable CS1591
        TreatmentType,
        #pragma warning restore CS1591
        [EnumMember(Value = "type_work_requests_it")]
        #pragma warning disable CS1591
        TypeWorkRequestsIt,
        #pragma warning restore CS1591
        [EnumMember(Value = "use_agency")]
        #pragma warning disable CS1591
        UseAgency,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_name")]
        #pragma warning disable CS1591
        UserName,
        #pragma warning restore CS1591
        [EnumMember(Value = "vendor_category")]
        #pragma warning disable CS1591
        VendorCategory,
        #pragma warning restore CS1591
        [EnumMember(Value = "vendor_type")]
        #pragma warning disable CS1591
        VendorType,
        #pragma warning restore CS1591
        [EnumMember(Value = "word_count")]
        #pragma warning disable CS1591
        WordCount,
        #pragma warning restore CS1591
    }
}
