// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCustomFieldSettingsForGoalOptFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "custom_field")]
        #pragma warning disable CS1591
        CustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.asana_created_field")]
        #pragma warning disable CS1591
        CustomFieldAsanaCreatedField,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.created_by")]
        #pragma warning disable CS1591
        CustomFieldCreatedBy,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.created_by.name")]
        #pragma warning disable CS1591
        CustomFieldCreatedByName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.currency_code")]
        #pragma warning disable CS1591
        CustomFieldCurrencyCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.custom_label")]
        #pragma warning disable CS1591
        CustomFieldCustomLabel,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.custom_label_position")]
        #pragma warning disable CS1591
        CustomFieldCustomLabelPosition,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.date_value")]
        #pragma warning disable CS1591
        CustomFieldDateValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.date_value.date")]
        #pragma warning disable CS1591
        CustomFieldDateValueDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.date_value.date_time")]
        #pragma warning disable CS1591
        CustomFieldDateValueDateTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.default_access_level")]
        #pragma warning disable CS1591
        CustomFieldDefaultAccessLevel,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.description")]
        #pragma warning disable CS1591
        CustomFieldDescription,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.display_value")]
        #pragma warning disable CS1591
        CustomFieldDisplayValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.enabled")]
        #pragma warning disable CS1591
        CustomFieldEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.enum_options")]
        #pragma warning disable CS1591
        CustomFieldEnumOptions,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.enum_options.color")]
        #pragma warning disable CS1591
        CustomFieldEnumOptionsColor,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.enum_options.enabled")]
        #pragma warning disable CS1591
        CustomFieldEnumOptionsEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.enum_options.name")]
        #pragma warning disable CS1591
        CustomFieldEnumOptionsName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.enum_value")]
        #pragma warning disable CS1591
        CustomFieldEnumValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.enum_value.color")]
        #pragma warning disable CS1591
        CustomFieldEnumValueColor,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.enum_value.enabled")]
        #pragma warning disable CS1591
        CustomFieldEnumValueEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.enum_value.name")]
        #pragma warning disable CS1591
        CustomFieldEnumValueName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.format")]
        #pragma warning disable CS1591
        CustomFieldFormat,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.has_notifications_enabled")]
        #pragma warning disable CS1591
        CustomFieldHasNotificationsEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.html_text_value")]
        #pragma warning disable CS1591
        CustomFieldHtmlTextValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.id_prefix")]
        #pragma warning disable CS1591
        CustomFieldIdPrefix,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.input_restrictions")]
        #pragma warning disable CS1591
        CustomFieldInputRestrictions,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.is_formula_field")]
        #pragma warning disable CS1591
        CustomFieldIsFormulaField,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.is_global_to_workspace")]
        #pragma warning disable CS1591
        CustomFieldIsGlobalToWorkspace,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.is_value_read_only")]
        #pragma warning disable CS1591
        CustomFieldIsValueReadOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.multi_enum_values")]
        #pragma warning disable CS1591
        CustomFieldMultiEnumValues,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.multi_enum_values.color")]
        #pragma warning disable CS1591
        CustomFieldMultiEnumValuesColor,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.multi_enum_values.enabled")]
        #pragma warning disable CS1591
        CustomFieldMultiEnumValuesEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.multi_enum_values.name")]
        #pragma warning disable CS1591
        CustomFieldMultiEnumValuesName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.name")]
        #pragma warning disable CS1591
        CustomFieldName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.number_value")]
        #pragma warning disable CS1591
        CustomFieldNumberValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.people_value")]
        #pragma warning disable CS1591
        CustomFieldPeopleValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.people_value.name")]
        #pragma warning disable CS1591
        CustomFieldPeopleValueName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.precision")]
        #pragma warning disable CS1591
        CustomFieldPrecision,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.privacy_setting")]
        #pragma warning disable CS1591
        CustomFieldPrivacySetting,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.reference_value")]
        #pragma warning disable CS1591
        CustomFieldReferenceValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.reference_value.name")]
        #pragma warning disable CS1591
        CustomFieldReferenceValueName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.representation_type")]
        #pragma warning disable CS1591
        CustomFieldRepresentationType,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.resource_subtype")]
        #pragma warning disable CS1591
        CustomFieldResourceSubtype,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.text_value")]
        #pragma warning disable CS1591
        CustomFieldTextValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_field.type")]
        #pragma warning disable CS1591
        CustomFieldType,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_important")]
        #pragma warning disable CS1591
        IsImportant,
        #pragma warning restore CS1591
        [EnumMember(Value = "offset")]
        #pragma warning disable CS1591
        Offset,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent")]
        #pragma warning disable CS1591
        Parent,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent.name")]
        #pragma warning disable CS1591
        ParentName,
        #pragma warning restore CS1591
        [EnumMember(Value = "path")]
        #pragma warning disable CS1591
        Path,
        #pragma warning restore CS1591
        [EnumMember(Value = "project")]
        #pragma warning disable CS1591
        Project,
        #pragma warning restore CS1591
        [EnumMember(Value = "project.name")]
        #pragma warning disable CS1591
        ProjectName,
        #pragma warning restore CS1591
        [EnumMember(Value = "uri")]
        #pragma warning disable CS1591
        Uri,
        #pragma warning restore CS1591
    }
}
