// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetGoalRelationshipOptFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "contribution_weight")]
        #pragma warning disable CS1591
        ContributionWeight,
        #pragma warning restore CS1591
        [EnumMember(Value = "resource_subtype")]
        #pragma warning disable CS1591
        ResourceSubtype,
        #pragma warning restore CS1591
        [EnumMember(Value = "supported_goal")]
        #pragma warning disable CS1591
        SupportedGoal,
        #pragma warning restore CS1591
        [EnumMember(Value = "supported_goal.name")]
        #pragma warning disable CS1591
        SupportedGoalName,
        #pragma warning restore CS1591
        [EnumMember(Value = "supported_goal.owner")]
        #pragma warning disable CS1591
        SupportedGoalOwner,
        #pragma warning restore CS1591
        [EnumMember(Value = "supported_goal.owner.name")]
        #pragma warning disable CS1591
        SupportedGoalOwnerName,
        #pragma warning restore CS1591
        [EnumMember(Value = "supporting_resource")]
        #pragma warning disable CS1591
        SupportingResource,
        #pragma warning restore CS1591
        [EnumMember(Value = "supporting_resource.name")]
        #pragma warning disable CS1591
        SupportingResourceName,
        #pragma warning restore CS1591
    }
}
