// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>
    /// A generic Asana Resource, containing a globally unique identifier.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GoalUpdateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object where each key is the GID of a custom field and its corresponding value is either an enum GID, string, number, or object (depending on the custom field type). See the [custom fields guide](/docs/custom-fields-guide) for details on creating and updating custom field values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.GoalUpdateRequest_custom_fields? CustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.GoalUpdateRequest_custom_fields CustomFields { get; set; }
#endif
        /// <summary>The localized day on which this goal is due. This takes a date with format `YYYY-MM-DD`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DueOn { get; set; }
#nullable restore
#else
        public string DueOn { get; set; }
#endif
        /// <summary>Globally unique identifier of the resource, as a string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gid { get; private set; }
#nullable restore
#else
        public string Gid { get; private set; }
#endif
        /// <summary>The notes of the goal with formatting as HTML.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HtmlNotes { get; set; }
#nullable restore
#else
        public string HtmlNotes { get; set; }
#endif
        /// <summary>*Conditional*. This property is only present when the `workspace` provided is an organization. Whether the goal belongs to the `workspace` (and is listed as part of the workspace’s goals) or not. If it isn’t a workspace-level goal, it is a team-level goal, and is associated with the goal’s team.</summary>
        public bool? IsWorkspaceLevel { get; set; }
        /// <summary>True if the goal is liked by the authorized user, false if not.</summary>
        public bool? Liked { get; set; }
        /// <summary>The name of the goal.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Free-form textual information associated with the goal (i.e. its description).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The `gid` of a user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>The base type of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; private set; }
#nullable restore
#else
        public string ResourceType { get; private set; }
#endif
        /// <summary>The day on which work for this goal begins, or null if the goal has no start date. This takes a date with `YYYY-MM-DD` format, and cannot be set unless there is an accompanying due date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartOn { get; set; }
#nullable restore
#else
        public string StartOn { get; set; }
#endif
        /// <summary>The current status of this goal. When the goal is open, its status can be `green`, `yellow`, and `red` to reflect &quot;On Track&quot;, &quot;At Risk&quot;, and &quot;Off Track&quot;, respectively. When the goal is closed, the value can be `missed`, `achieved`, `partial`, or `dropped`.*Note* you can only write to this property if `metric` is set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>*Conditional*. This property is only present when the `workspace` provided is an organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Team { get; set; }
#nullable restore
#else
        public string Team { get; set; }
#endif
        /// <summary>The `gid` of a time period.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimePeriod { get; set; }
#nullable restore
#else
        public string TimePeriod { get; set; }
#endif
        /// <summary>The `gid` of a workspace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Workspace { get; set; }
#nullable restore
#else
        public string Workspace { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Models.GoalUpdateRequest"/> and sets the default values.
        /// </summary>
        public GoalUpdateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.GoalUpdateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Asana.OpenApiClient.Models.GoalUpdateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Asana.OpenApiClient.Models.GoalUpdateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_fields", n => { CustomFields = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.GoalUpdateRequest_custom_fields>(global::Soenneker.Asana.OpenApiClient.Models.GoalUpdateRequest_custom_fields.CreateFromDiscriminatorValue); } },
                { "due_on", n => { DueOn = n.GetStringValue(); } },
                { "gid", n => { Gid = n.GetStringValue(); } },
                { "html_notes", n => { HtmlNotes = n.GetStringValue(); } },
                { "is_workspace_level", n => { IsWorkspaceLevel = n.GetBoolValue(); } },
                { "liked", n => { Liked = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "start_on", n => { StartOn = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "team", n => { Team = n.GetStringValue(); } },
                { "time_period", n => { TimePeriod = n.GetStringValue(); } },
                { "workspace", n => { Workspace = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.GoalUpdateRequest_custom_fields>("custom_fields", CustomFields);
            writer.WriteStringValue("due_on", DueOn);
            writer.WriteStringValue("html_notes", HtmlNotes);
            writer.WriteBoolValue("is_workspace_level", IsWorkspaceLevel);
            writer.WriteBoolValue("liked", Liked);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("notes", Notes);
            writer.WriteStringValue("owner", Owner);
            writer.WriteStringValue("start_on", StartOn);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("team", Team);
            writer.WriteStringValue("time_period", TimePeriod);
            writer.WriteStringValue("workspace", Workspace);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
