// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>The privacy setting of the goal.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GoalResponsePrivacySetting
    {
        [EnumMember(Value = "public_to_workspace")]
        #pragma warning disable CS1591
        PublicToWorkspace,
        #pragma warning restore CS1591
        [EnumMember(Value = "members_only")]
        #pragma warning disable CS1591
        MembersOnly,
        #pragma warning restore CS1591
    }
}
