// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf1"/>, <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf2"/>, <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf3"/>, <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf4"/>, <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf5"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MembershipResponse : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf1? MembershipResponseAnyOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf1 MembershipResponseAnyOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf2? MembershipResponseAnyOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf2 MembershipResponseAnyOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf3? MembershipResponseAnyOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf3 MembershipResponseAnyOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf4? MembershipResponseAnyOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf4 MembershipResponseAnyOf4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf5? MembershipResponseAnyOf5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf5 MembershipResponseAnyOf5 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.MembershipResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Asana.OpenApiClient.Models.MembershipResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Asana.OpenApiClient.Models.MembershipResponse();
            result.MembershipResponseAnyOf1 = new global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf1();
            result.MembershipResponseAnyOf2 = new global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf2();
            result.MembershipResponseAnyOf3 = new global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf3();
            result.MembershipResponseAnyOf4 = new global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf4();
            result.MembershipResponseAnyOf5 = new global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf5();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MembershipResponseAnyOf1 != null || MembershipResponseAnyOf2 != null || MembershipResponseAnyOf3 != null || MembershipResponseAnyOf4 != null || MembershipResponseAnyOf5 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MembershipResponseAnyOf1, MembershipResponseAnyOf2, MembershipResponseAnyOf3, MembershipResponseAnyOf4, MembershipResponseAnyOf5);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.MembershipResponseAnyOf1>(null, MembershipResponseAnyOf1, MembershipResponseAnyOf2, MembershipResponseAnyOf3, MembershipResponseAnyOf4, MembershipResponseAnyOf5);
        }
    }
}
#pragma warning restore CS0618
