// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>The icon for a project.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectUpdateRequest_icon
    {
        [EnumMember(Value = "list")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
        [EnumMember(Value = "board")]
        #pragma warning disable CS1591
        Board,
        #pragma warning restore CS1591
        [EnumMember(Value = "timeline")]
        #pragma warning disable CS1591
        Timeline,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar")]
        #pragma warning disable CS1591
        Calendar,
        #pragma warning restore CS1591
        [EnumMember(Value = "rocket")]
        #pragma warning disable CS1591
        Rocket,
        #pragma warning restore CS1591
        [EnumMember(Value = "people")]
        #pragma warning disable CS1591
        People,
        #pragma warning restore CS1591
        [EnumMember(Value = "graph")]
        #pragma warning disable CS1591
        Graph,
        #pragma warning restore CS1591
        [EnumMember(Value = "star")]
        #pragma warning disable CS1591
        Star,
        #pragma warning restore CS1591
        [EnumMember(Value = "bug")]
        #pragma warning disable CS1591
        Bug,
        #pragma warning restore CS1591
        [EnumMember(Value = "light_bulb")]
        #pragma warning disable CS1591
        Light_bulb,
        #pragma warning restore CS1591
        [EnumMember(Value = "globe")]
        #pragma warning disable CS1591
        Globe,
        #pragma warning restore CS1591
        [EnumMember(Value = "gear")]
        #pragma warning disable CS1591
        Gear,
        #pragma warning restore CS1591
        [EnumMember(Value = "notebook")]
        #pragma warning disable CS1591
        Notebook,
        #pragma warning restore CS1591
        [EnumMember(Value = "computer")]
        #pragma warning disable CS1591
        Computer,
        #pragma warning restore CS1591
        [EnumMember(Value = "check")]
        #pragma warning disable CS1591
        Check,
        #pragma warning restore CS1591
        [EnumMember(Value = "target")]
        #pragma warning disable CS1591
        Target,
        #pragma warning restore CS1591
        [EnumMember(Value = "html")]
        #pragma warning disable CS1591
        Html,
        #pragma warning restore CS1591
        [EnumMember(Value = "megaphone")]
        #pragma warning disable CS1591
        Megaphone,
        #pragma warning restore CS1591
        [EnumMember(Value = "chat_bubbles")]
        #pragma warning disable CS1591
        Chat_bubbles,
        #pragma warning restore CS1591
        [EnumMember(Value = "briefcase")]
        #pragma warning disable CS1591
        Briefcase,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_layout")]
        #pragma warning disable CS1591
        Page_layout,
        #pragma warning restore CS1591
        [EnumMember(Value = "mountain_flag")]
        #pragma warning disable CS1591
        Mountain_flag,
        #pragma warning restore CS1591
        [EnumMember(Value = "puzzle")]
        #pragma warning disable CS1591
        Puzzle,
        #pragma warning restore CS1591
        [EnumMember(Value = "presentation")]
        #pragma warning disable CS1591
        Presentation,
        #pragma warning restore CS1591
        [EnumMember(Value = "line_and_symbols")]
        #pragma warning disable CS1591
        Line_and_symbols,
        #pragma warning restore CS1591
        [EnumMember(Value = "speed_dial")]
        #pragma warning disable CS1591
        Speed_dial,
        #pragma warning restore CS1591
        [EnumMember(Value = "ribbon")]
        #pragma warning disable CS1591
        Ribbon,
        #pragma warning restore CS1591
        [EnumMember(Value = "shoe")]
        #pragma warning disable CS1591
        Shoe,
        #pragma warning restore CS1591
        [EnumMember(Value = "shopping_basket")]
        #pragma warning disable CS1591
        Shopping_basket,
        #pragma warning restore CS1591
        [EnumMember(Value = "map")]
        #pragma warning disable CS1591
        Map,
        #pragma warning restore CS1591
        [EnumMember(Value = "ticket")]
        #pragma warning disable CS1591
        Ticket,
        #pragma warning restore CS1591
        [EnumMember(Value = "coins")]
        #pragma warning disable CS1591
        Coins,
        #pragma warning restore CS1591
    }
}
