// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>The default access for users or teams who join or are added as members to the project.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectRequest_default_access_level
    {
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "editor")]
        #pragma warning disable CS1591
        Editor,
        #pragma warning restore CS1591
        [EnumMember(Value = "commenter")]
        #pragma warning disable CS1591
        Commenter,
        #pragma warning restore CS1591
        [EnumMember(Value = "viewer")]
        #pragma warning disable CS1591
        Viewer,
        #pragma warning restore CS1591
    }
}
