// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>The color associated with the status update.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectRequest_current_status_color
    {
        [EnumMember(Value = "green")]
        #pragma warning disable CS1591
        Green,
        #pragma warning restore CS1591
        [EnumMember(Value = "yellow")]
        #pragma warning disable CS1591
        Yellow,
        #pragma warning restore CS1591
        [EnumMember(Value = "red")]
        #pragma warning disable CS1591
        Red,
        #pragma warning restore CS1591
        [EnumMember(Value = "blue")]
        #pragma warning disable CS1591
        Blue,
        #pragma warning restore CS1591
        [EnumMember(Value = "complete")]
        #pragma warning disable CS1591
        Complete,
        #pragma warning restore CS1591
    }
}
