// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>
    /// A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier.A *project* represents a prioritized list of tasks in Asana or a board with columns of tasks represented as cards. It exists in a single workspace or organization and is accessible to a subset of users in that workspace or organization, depending on its permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectUpdateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>True if the project is archived, false if not. Archived projects do not show in the UI by default and may be treated differently for queries.</summary>
        public bool? Archived { get; set; }
        /// <summary>Color of the project.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_color? Color { get; set; }
        /// <summary>The time at which this resource was created.</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier.*Deprecated: new integrations should prefer the `status_update` resource.*A *project status* is an update on the progress of a particular project, and is sent out to all project followers when created. These updates include both text describing the update and a color code intended to represent the overall state of the project: &quot;green&quot; for projects that are on track, &quot;yellow&quot; for projects at risk, and &quot;red&quot; for projects that are behind.A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier.*Deprecated: new integrations should prefer the `status_update` resource.*A *project status* is an update on the progress of a particular project, and is sent out to all project followers when created. These updates include both text describing the update and a color code intended to represent the overall state of the project: &quot;green&quot; for projects that are on track, &quot;yellow&quot; for projects at risk, and &quot;red&quot; for projects that are behind.*Deprecated: new integrations should prefer the `current_status_update` resource.*</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_current_status? CurrentStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_current_status CurrentStatus { get; set; }
#endif
        /// <summary>A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier.A *status update* is an update on the progress of a particular project, portfolio, or goal, and is sent out to all of its parent&apos;s followers when created. These updates include both text describing the update and a `status_type` intended to represent the overall state of the object.A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier.A *status update* is an update on the progress of a particular project, portfolio, or goal, and is sent out to all of its parent&apos;s followers when created. These updates include both text describing the update and a `status_type` intended to represent the overall state of the object.The latest `status_update` posted to this project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_current_status_update? CurrentStatusUpdate { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_current_status_update CurrentStatusUpdate { get; set; }
#endif
        /// <summary>An object where each key is the GID of a custom field and its corresponding value is either an enum GID, string, number, or object (depending on the custom field type). See the [custom fields guide](/docs/custom-fields-guide) for details on creating and updating custom field values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_custom_fields? CustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_custom_fields CustomFields { get; set; }
#endif
        /// <summary>Array of custom field definitions that are enabled for the project. These represent which custom fields are available to be used on tasks within the project, but do not include any values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_custom_field_settings>? CustomFieldSettings { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_custom_field_settings> CustomFieldSettings { get; private set; }
#endif
        /// <summary>The default access for users or teams who join or are added as members to the project.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_default_access_level? DefaultAccessLevel { get; set; }
        /// <summary>The default view (list, board, calendar, or timeline) of a project.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_default_view? DefaultView { get; set; }
        /// <summary>*Deprecated: new integrations should prefer the `due_on` field.*</summary>
        public Date? DueDate { get; set; }
        /// <summary>The day on which this project is due. This takes a date with format YYYY-MM-DD.</summary>
        public Date? DueOn { get; set; }
        /// <summary>*Create-only*. Comma separated string of users. Followers are a subset of members who have opted in to receive &quot;tasks added&quot; notifications for a project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Followers { get; set; }
#nullable restore
#else
        public string Followers { get; set; }
#endif
        /// <summary>Globally unique identifier of the resource, as a string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gid { get; private set; }
#nullable restore
#else
        public string Gid { get; private set; }
#endif
        /// <summary>[Opt In](/docs/inputoutput-options). The notes of the project with formatting as HTML.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HtmlNotes { get; set; }
#nullable restore
#else
        public string HtmlNotes { get; set; }
#endif
        /// <summary>The icon for a project.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_icon? Icon { get; set; }
        /// <summary>Array of users who are members of this project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_members>? Members { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_members> Members { get; private set; }
#endif
        /// <summary>The minimum access level needed for project members to modify this project&apos;s workflow and appearance.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_minimum_access_level_for_customization? MinimumAccessLevelForCustomization { get; set; }
        /// <summary>The minimum access level needed for project members to share the project and manage project memberships.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_minimum_access_level_for_sharing? MinimumAccessLevelForSharing { get; set; }
        /// <summary>The time at which this project was last modified.*Note: This does not currently reflect any changes in associations such as tasks or comments that may have been added or removed from the project.*</summary>
        public DateTimeOffset? ModifiedAt { get; private set; }
        /// <summary>Name of the project. This is generally a short sentence fragment that fits on a line in the UI for maximum readability. However, it can be longer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Free-form textual information associated with the project (ie., its description).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The current owner of the project, may be null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>The privacy setting of the project. *Note: Administrators in your organization may restrict the values of `privacy_setting`.* The value `private_to_team` is deprecated. Use `POST /memberships` to share a project with a team after creation.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_privacy_setting? PrivacySetting { get; set; }
        /// <summary>*Deprecated:* new integrations use `privacy_setting` instead.</summary>
        [Obsolete("")]
        public bool? Public { get; set; }
        /// <summary>The base type of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; private set; }
#nullable restore
#else
        public string ResourceType { get; private set; }
#endif
        /// <summary>The day on which work for this project begins, or null if the project has no start date. This takes a date with `YYYY-MM-DD` format. *Note: `due_on` or `due_at` must be present in the request when setting or unsetting the `start_on` parameter. Additionally, `start_on` and `due_on` cannot be the same date.*</summary>
        public Date? StartOn { get; set; }
        /// <summary>*Deprecated:* Updating the team a project is shared with is deprecated. Use `POST /memberships` with `{ parent: project, member: team }` instead to manage team sharing.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Team { get; set; }
#nullable restore
#else
        public string Team { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest"/> and sets the default values.
        /// </summary>
        public ProjectUpdateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "color", n => { Color = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_color>(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "current_status", n => { CurrentStatus = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_current_status>(global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_current_status.CreateFromDiscriminatorValue); } },
                { "current_status_update", n => { CurrentStatusUpdate = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_current_status_update>(global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_current_status_update.CreateFromDiscriminatorValue); } },
                { "custom_field_settings", n => { CustomFieldSettings = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_custom_field_settings>(global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_custom_field_settings.CreateFromDiscriminatorValue)?.AsList(); } },
                { "custom_fields", n => { CustomFields = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_custom_fields>(global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_custom_fields.CreateFromDiscriminatorValue); } },
                { "default_access_level", n => { DefaultAccessLevel = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_default_access_level>(); } },
                { "default_view", n => { DefaultView = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_default_view>(); } },
                { "due_date", n => { DueDate = n.GetDateValue(); } },
                { "due_on", n => { DueOn = n.GetDateValue(); } },
                { "followers", n => { Followers = n.GetStringValue(); } },
                { "gid", n => { Gid = n.GetStringValue(); } },
                { "html_notes", n => { HtmlNotes = n.GetStringValue(); } },
                { "icon", n => { Icon = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_icon>(); } },
                { "members", n => { Members = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_members>(global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_members.CreateFromDiscriminatorValue)?.AsList(); } },
                { "minimum_access_level_for_customization", n => { MinimumAccessLevelForCustomization = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_minimum_access_level_for_customization>(); } },
                { "minimum_access_level_for_sharing", n => { MinimumAccessLevelForSharing = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_minimum_access_level_for_sharing>(); } },
                { "modified_at", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "privacy_setting", n => { PrivacySetting = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_privacy_setting>(); } },
                { "public", n => { Public = n.GetBoolValue(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "start_on", n => { StartOn = n.GetDateValue(); } },
                { "team", n => { Team = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_color>("color", Color);
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_current_status>("current_status", CurrentStatus);
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_current_status_update>("current_status_update", CurrentStatusUpdate);
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_custom_fields>("custom_fields", CustomFields);
            writer.WriteEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_default_access_level>("default_access_level", DefaultAccessLevel);
            writer.WriteEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_default_view>("default_view", DefaultView);
            writer.WriteDateValue("due_date", DueDate);
            writer.WriteDateValue("due_on", DueOn);
            writer.WriteStringValue("followers", Followers);
            writer.WriteStringValue("html_notes", HtmlNotes);
            writer.WriteEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_icon>("icon", Icon);
            writer.WriteEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_minimum_access_level_for_customization>("minimum_access_level_for_customization", MinimumAccessLevelForCustomization);
            writer.WriteEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_minimum_access_level_for_sharing>("minimum_access_level_for_sharing", MinimumAccessLevelForSharing);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("notes", Notes);
            writer.WriteStringValue("owner", Owner);
            writer.WriteEnumValue<global::Soenneker.Asana.OpenApiClient.Models.ProjectUpdateRequest_privacy_setting>("privacy_setting", PrivacySetting);
            writer.WriteBoolValue("public", Public);
            writer.WriteDateValue("start_on", StartOn);
            writer.WriteStringValue("team", Team);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
