// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>The privacy setting of the project. *Note: Administrators in your organization may restrict the values of `privacy_setting`.* The value `private_to_team` is deprecated. Use `POST /memberships` to share a project with a team after creation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectRequest_privacy_setting
    {
        [EnumMember(Value = "public_to_workspace")]
        #pragma warning disable CS1591
        Public_to_workspace,
        #pragma warning restore CS1591
        [EnumMember(Value = "private_to_team")]
        #pragma warning disable CS1591
        Private_to_team,
        #pragma warning restore CS1591
        [EnumMember(Value = "private")]
        #pragma warning disable CS1591
        Private,
        #pragma warning restore CS1591
    }
}
