// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.The `resource_subtype`s for `status` objects represent the type of their parent.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StatusUpdateRequest_resource_subtype
    {
        [EnumMember(Value = "project_status_update")]
        #pragma warning disable CS1591
        Project_status_update,
        #pragma warning restore CS1591
        [EnumMember(Value = "portfolio_status_update")]
        #pragma warning disable CS1591
        Portfolio_status_update,
        #pragma warning restore CS1591
        [EnumMember(Value = "goal_status_update")]
        #pragma warning disable CS1591
        Goal_status_update,
        #pragma warning restore CS1591
    }
}
