// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>
    /// A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier.A *status update* is an update on the progress of a particular project, portfolio, or goal, and is sent out to all of its parent&apos;s followers when created. These updates include both text describing the update and a `status_type` intended to represent the overall state of the object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusUpdateResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier.A *user* object represents an account in Asana that can be given access to various workspaces, projects, and tasks.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_author? Author { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_author Author { get; set; }
#endif
        /// <summary>The time at which this resource was created.</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier.A *user* object represents an account in Asana that can be given access to various workspaces, projects, and tasks.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_created_by? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_created_by CreatedBy { get; set; }
#endif
        /// <summary>Globally unique identifier of the resource, as a string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gid { get; private set; }
#nullable restore
#else
        public string Gid { get; private set; }
#endif
        /// <summary>*Deprecated - please use liked instead* True if the status is hearted by the authorized user, false if not.</summary>
        public bool? Hearted { get; private set; }
        /// <summary>*Deprecated - please use likes instead* Array of likes for users who have hearted this status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_hearts>? Hearts { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_hearts> Hearts { get; private set; }
#endif
        /// <summary>[Opt In](/docs/inputoutput-options). The text content of the status update with formatting as HTML.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HtmlText { get; set; }
#nullable restore
#else
        public string HtmlText { get; set; }
#endif
        /// <summary>True if the status is liked by the authorized user, false if not.</summary>
        public bool? Liked { get; set; }
        /// <summary>Array of likes for users who have liked this status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_likes>? Likes { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_likes> Likes { get; private set; }
#endif
        /// <summary>The time at which this project status was last modified.*Note: This does not currently reflect any changes in associations such as comments that may have been added or removed from the status.*</summary>
        public DateTimeOffset? ModifiedAt { get; private set; }
        /// <summary>*Deprecated - please use likes instead* The number of users who have hearted this status.</summary>
        public int? NumHearts { get; private set; }
        /// <summary>The number of users who have liked this status.</summary>
        public int? NumLikes { get; private set; }
        /// <summary>A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier.A *project* represents a prioritized list of tasks in Asana or a board with columns of tasks represented as cards. It exists in a single workspace or organization and is accessible to a subset of users in that workspace or organization, depending on its permissions.A generic Asana Resource, containing a globally unique identifier.A generic Asana Resource, containing a globally unique identifier.A *project* represents a prioritized list of tasks in Asana or a board with columns of tasks represented as cards. It exists in a single workspace or organization and is accessible to a subset of users in that workspace or organization, depending on its permissions.The parent of the status update. This can be a project, goal or portfolio, and indicates that this status was sent on that object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_parent? Parent { get; set; }
#nullable restore
#else
        public global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_parent Parent { get; set; }
#endif
        /// <summary>Summary of emoji reactions on this status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_reaction_summary>? ReactionSummary { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_reaction_summary> ReactionSummary { get; private set; }
#endif
        /// <summary>The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.The `resource_subtype`s for `status` objects represent the type of their parent.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_resource_subtype? ResourceSubtype { get; private set; }
        /// <summary>The base type of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; private set; }
#nullable restore
#else
        public string ResourceType { get; private set; }
#endif
        /// <summary>The type associated with the status update. This represents the current state of the object this object is on.The valid values for `status_type` depend on the parent of the status update:- Projects: `on_track`, `at_risk`, `off_track`, `on_hold`, `complete`, `dropped`.- Portfolios: `on_track`, `at_risk`, `off_track`, `on_hold`, `complete`, `dropped`.- Goals: `on_track`, `at_risk`, `off_track`, `achieved`, `partial`, `missed`, `dropped`.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_status_type? StatusType { get; set; }
        /// <summary>The text content of the status update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The title of the status update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse"/> and sets the default values.
        /// </summary>
        public StatusUpdateResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "author", n => { Author = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_author>(global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_author.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_created_by>(global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_created_by.CreateFromDiscriminatorValue); } },
                { "gid", n => { Gid = n.GetStringValue(); } },
                { "hearted", n => { Hearted = n.GetBoolValue(); } },
                { "hearts", n => { Hearts = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_hearts>(global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_hearts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "html_text", n => { HtmlText = n.GetStringValue(); } },
                { "liked", n => { Liked = n.GetBoolValue(); } },
                { "likes", n => { Likes = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_likes>(global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_likes.CreateFromDiscriminatorValue)?.AsList(); } },
                { "modified_at", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "num_hearts", n => { NumHearts = n.GetIntValue(); } },
                { "num_likes", n => { NumLikes = n.GetIntValue(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_parent>(global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_parent.CreateFromDiscriminatorValue); } },
                { "reaction_summary", n => { ReactionSummary = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_reaction_summary>(global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_reaction_summary.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resource_subtype", n => { ResourceSubtype = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_resource_subtype>(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "status_type", n => { StatusType = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_status_type>(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_author>("author", Author);
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_created_by>("created_by", CreatedBy);
            writer.WriteStringValue("html_text", HtmlText);
            writer.WriteBoolValue("liked", Liked);
            writer.WriteObjectValue<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_parent>("parent", Parent);
            writer.WriteEnumValue<global::Soenneker.Asana.OpenApiClient.Models.StatusUpdateResponse_status_type>("status_type", StatusType);
            writer.WriteStringValue("text", Text);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
