// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>The type associated with the status update. This represents the current state of the object this object is on.The valid values for `status_type` depend on the parent of the status update:- Projects: `on_track`, `at_risk`, `off_track`, `on_hold`, `complete`, `dropped`.- Portfolios: `on_track`, `at_risk`, `off_track`, `on_hold`, `complete`, `dropped`.- Goals: `on_track`, `at_risk`, `off_track`, `achieved`, `partial`, `missed`, `dropped`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StatusUpdateRequest_status_type
    {
        [EnumMember(Value = "on_track")]
        #pragma warning disable CS1591
        On_track,
        #pragma warning restore CS1591
        [EnumMember(Value = "at_risk")]
        #pragma warning disable CS1591
        At_risk,
        #pragma warning restore CS1591
        [EnumMember(Value = "off_track")]
        #pragma warning disable CS1591
        Off_track,
        #pragma warning restore CS1591
        [EnumMember(Value = "on_hold")]
        #pragma warning disable CS1591
        On_hold,
        #pragma warning restore CS1591
        [EnumMember(Value = "complete")]
        #pragma warning disable CS1591
        Complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "achieved")]
        #pragma warning disable CS1591
        Achieved,
        #pragma warning restore CS1591
        [EnumMember(Value = "partial")]
        #pragma warning disable CS1591
        Partial,
        #pragma warning restore CS1591
        [EnumMember(Value = "missed")]
        #pragma warning disable CS1591
        Missed,
        #pragma warning restore CS1591
        [EnumMember(Value = "dropped")]
        #pragma warning disable CS1591
        Dropped,
        #pragma warning restore CS1591
    }
}
