// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>Color of the tag.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TagUpdateRequest_color
    {
        [EnumMember(Value = "dark-pink")]
        #pragma warning disable CS1591
        DarkPink,
        #pragma warning restore CS1591
        [EnumMember(Value = "dark-green")]
        #pragma warning disable CS1591
        DarkGreen,
        #pragma warning restore CS1591
        [EnumMember(Value = "dark-blue")]
        #pragma warning disable CS1591
        DarkBlue,
        #pragma warning restore CS1591
        [EnumMember(Value = "dark-red")]
        #pragma warning disable CS1591
        DarkRed,
        #pragma warning restore CS1591
        [EnumMember(Value = "dark-teal")]
        #pragma warning disable CS1591
        DarkTeal,
        #pragma warning restore CS1591
        [EnumMember(Value = "dark-brown")]
        #pragma warning disable CS1591
        DarkBrown,
        #pragma warning restore CS1591
        [EnumMember(Value = "dark-orange")]
        #pragma warning disable CS1591
        DarkOrange,
        #pragma warning restore CS1591
        [EnumMember(Value = "dark-purple")]
        #pragma warning disable CS1591
        DarkPurple,
        #pragma warning restore CS1591
        [EnumMember(Value = "dark-warm-gray")]
        #pragma warning disable CS1591
        DarkWarmGray,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-pink")]
        #pragma warning disable CS1591
        LightPink,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-green")]
        #pragma warning disable CS1591
        LightGreen,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-blue")]
        #pragma warning disable CS1591
        LightBlue,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-red")]
        #pragma warning disable CS1591
        LightRed,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-teal")]
        #pragma warning disable CS1591
        LightTeal,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-brown")]
        #pragma warning disable CS1591
        LightBrown,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-orange")]
        #pragma warning disable CS1591
        LightOrange,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-purple")]
        #pragma warning disable CS1591
        LightPurple,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-warm-gray")]
        #pragma warning disable CS1591
        LightWarmGray,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
