// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TaskTemplateResponse_template : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Array of attachments that will be added to the task created from this template</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_attachments>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_attachments> Attachments { get; set; }
#endif
        /// <summary>Array of custom fields that will be added to the task created from this template</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_custom_fields>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_custom_fields> CustomFields { get; set; }
#endif
        /// <summary>Array of task templates that the task created from this template will depend on</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_dependencies>? Dependencies { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_dependencies> Dependencies { get; set; }
#endif
        /// <summary>Array of task templates that will depend on the task created from this template</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_dependents>? Dependents { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_dependents> Dependents { get; set; }
#endif
        /// <summary>Description of the task that will be created from this template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The time of day that the task will be due</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DueTime { get; set; }
#nullable restore
#else
        public string DueTime { get; set; }
#endif
        /// <summary>Array of users that will be added as followers to the task created from this template</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_followers>? Followers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_followers> Followers { get; set; }
#endif
        /// <summary>HTML description of the task that will be created from this template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HtmlDescription { get; set; }
#nullable restore
#else
        public string HtmlDescription { get; set; }
#endif
        /// <summary>Array of projects that the task created from this template will be added to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_memberships>? Memberships { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_memberships> Memberships { get; set; }
#endif
        /// <summary>Name of the task that will be created from this template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The number of days after the task has been instantiated on which that the task will be due</summary>
        public int? RelativeDueOn { get; set; }
        /// <summary>The number of days after the task has been instantiated on which that the task will start</summary>
        public int? RelativeStartOn { get; set; }
        /// <summary>Array of subtasks that will be added to the task created from this template</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_subtasks>? Subtasks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_subtasks> Subtasks { get; set; }
#endif
        /// <summary>The subtype of the task that will be created from this template.</summary>
        public global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_task_resource_subtype? TaskResourceSubtype { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template"/> and sets the default values.
        /// </summary>
        public TaskTemplateResponse_template()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_attachments>(global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_attachments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_custom_fields>(global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_custom_fields.CreateFromDiscriminatorValue)?.AsList(); } },
                { "dependencies", n => { Dependencies = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_dependencies>(global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_dependencies.CreateFromDiscriminatorValue)?.AsList(); } },
                { "dependents", n => { Dependents = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_dependents>(global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_dependents.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "due_time", n => { DueTime = n.GetStringValue(); } },
                { "followers", n => { Followers = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_followers>(global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_followers.CreateFromDiscriminatorValue)?.AsList(); } },
                { "html_description", n => { HtmlDescription = n.GetStringValue(); } },
                { "memberships", n => { Memberships = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_memberships>(global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_memberships.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "relative_due_on", n => { RelativeDueOn = n.GetIntValue(); } },
                { "relative_start_on", n => { RelativeStartOn = n.GetIntValue(); } },
                { "subtasks", n => { Subtasks = n.GetCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_subtasks>(global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_subtasks.CreateFromDiscriminatorValue)?.AsList(); } },
                { "task_resource_subtype", n => { TaskResourceSubtype = n.GetEnumValue<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_task_resource_subtype>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_attachments>("attachments", Attachments);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_custom_fields>("custom_fields", CustomFields);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_dependencies>("dependencies", Dependencies);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_dependents>("dependents", Dependents);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("due_time", DueTime);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_followers>("followers", Followers);
            writer.WriteStringValue("html_description", HtmlDescription);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_memberships>("memberships", Memberships);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("relative_due_on", RelativeDueOn);
            writer.WriteIntValue("relative_start_on", RelativeStartOn);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_subtasks>("subtasks", Subtasks);
            writer.WriteEnumValue<global::Soenneker.Asana.OpenApiClient.Models.TaskTemplateResponse_template_task_resource_subtype>("task_resource_subtype", TaskResourceSubtype);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
