// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>*Deprecated* Scheduling status of this task for the user it is assigned to. This field can only be set if the assignee is non-null. Setting this field to &quot;inbox&quot; or &quot;upcoming&quot; inserts it at the top of the section, while the other options will insert at the bottom.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskResponse_assignee_status
    {
        [EnumMember(Value = "today")]
        #pragma warning disable CS1591
        Today,
        #pragma warning restore CS1591
        [EnumMember(Value = "upcoming")]
        #pragma warning disable CS1591
        Upcoming,
        #pragma warning restore CS1591
        [EnumMember(Value = "later")]
        #pragma warning disable CS1591
        Later,
        #pragma warning restore CS1591
        [EnumMember(Value = "new")]
        #pragma warning disable CS1591
        New,
        #pragma warning restore CS1591
        [EnumMember(Value = "inbox")]
        #pragma warning disable CS1591
        Inbox,
        #pragma warning restore CS1591
    }
}
