// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>This field tells the type of the custom field.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TeamResponseCustomFieldSettingsItemCustomFieldRepresentationType
    {
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "enum")]
        #pragma warning disable CS1591
        EnumValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi_enum")]
        #pragma warning disable CS1591
        MultiEnum,
        #pragma warning restore CS1591
        [EnumMember(Value = "number")]
        #pragma warning disable CS1591
        Number,
        #pragma warning restore CS1591
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "people")]
        #pragma warning disable CS1591
        People,
        #pragma warning restore CS1591
        [EnumMember(Value = "formula")]
        #pragma warning disable CS1591
        Formula,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_id")]
        #pragma warning disable CS1591
        CustomId,
        #pragma warning restore CS1591
        [EnumMember(Value = "reference")]
        #pragma warning disable CS1591
        Reference,
        #pragma warning restore CS1591
    }
}
