// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>The default access level when inviting new members to the custom field. This isn&apos;t applied when the `privacy_setting` is `private`, or the user is a guest. For local fields in a project or portfolio, the user must additionally have permission to modify the container itself.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TeamResponse_custom_field_settings_custom_field_default_access_level
    {
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "editor")]
        #pragma warning disable CS1591
        Editor,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
    }
}
