// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>The visibility of the team to users in the same organization</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TeamResponse_visibility
    {
        [EnumMember(Value = "secret")]
        #pragma warning disable CS1591
        Secret,
        #pragma warning restore CS1591
        [EnumMember(Value = "request_to_join")]
        #pragma warning disable CS1591
        Request_to_join,
        #pragma warning restore CS1591
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
    }
}
