// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>*Optional*. The current billable status of the entry.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateTimeTrackingEntryRequest_billable_status
    {
        [EnumMember(Value = "billable")]
        #pragma warning disable CS1591
        Billable,
        #pragma warning restore CS1591
        [EnumMember(Value = "nonBillable")]
        #pragma warning disable CS1591
        NonBillable,
        #pragma warning restore CS1591
        [EnumMember(Value = "notApplicable")]
        #pragma warning disable CS1591
        NotApplicable,
        #pragma warning restore CS1591
    }
}
