// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateUserOptFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "custom_fields")]
        #pragma warning disable CS1591
        CustomFields,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.date_value")]
        #pragma warning disable CS1591
        CustomFieldsDateValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.date_value.date")]
        #pragma warning disable CS1591
        CustomFieldsDateValueDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.date_value.date_time")]
        #pragma warning disable CS1591
        CustomFieldsDateValueDateTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.display_value")]
        #pragma warning disable CS1591
        CustomFieldsDisplayValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.enabled")]
        #pragma warning disable CS1591
        CustomFieldsEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.enum_options")]
        #pragma warning disable CS1591
        CustomFieldsEnumOptions,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.enum_options.color")]
        #pragma warning disable CS1591
        CustomFieldsEnumOptionsColor,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.enum_options.enabled")]
        #pragma warning disable CS1591
        CustomFieldsEnumOptionsEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.enum_options.name")]
        #pragma warning disable CS1591
        CustomFieldsEnumOptionsName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.enum_value")]
        #pragma warning disable CS1591
        CustomFieldsEnumValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.enum_value.color")]
        #pragma warning disable CS1591
        CustomFieldsEnumValueColor,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.enum_value.enabled")]
        #pragma warning disable CS1591
        CustomFieldsEnumValueEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.enum_value.name")]
        #pragma warning disable CS1591
        CustomFieldsEnumValueName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.id_prefix")]
        #pragma warning disable CS1591
        CustomFieldsIdPrefix,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.input_restrictions")]
        #pragma warning disable CS1591
        CustomFieldsInputRestrictions,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.is_formula_field")]
        #pragma warning disable CS1591
        CustomFieldsIsFormulaField,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.multi_enum_values")]
        #pragma warning disable CS1591
        CustomFieldsMultiEnumValues,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.multi_enum_values.color")]
        #pragma warning disable CS1591
        CustomFieldsMultiEnumValuesColor,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.multi_enum_values.enabled")]
        #pragma warning disable CS1591
        CustomFieldsMultiEnumValuesEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.multi_enum_values.name")]
        #pragma warning disable CS1591
        CustomFieldsMultiEnumValuesName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.name")]
        #pragma warning disable CS1591
        CustomFieldsName,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.number_value")]
        #pragma warning disable CS1591
        CustomFieldsNumberValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.representation_type")]
        #pragma warning disable CS1591
        CustomFieldsRepresentationType,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.text_value")]
        #pragma warning disable CS1591
        CustomFieldsTextValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields.type")]
        #pragma warning disable CS1591
        CustomFieldsType,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "photo")]
        #pragma warning disable CS1591
        Photo,
        #pragma warning restore CS1591
        [EnumMember(Value = "photo.image_1024x1024")]
        #pragma warning disable CS1591
        PhotoImage1024X1024,
        #pragma warning restore CS1591
        [EnumMember(Value = "photo.image_128x128")]
        #pragma warning disable CS1591
        PhotoImage128X128,
        #pragma warning restore CS1591
        [EnumMember(Value = "photo.image_21x21")]
        #pragma warning disable CS1591
        PhotoImage21X21,
        #pragma warning restore CS1591
        [EnumMember(Value = "photo.image_27x27")]
        #pragma warning disable CS1591
        PhotoImage27X27,
        #pragma warning restore CS1591
        [EnumMember(Value = "photo.image_36x36")]
        #pragma warning disable CS1591
        PhotoImage36X36,
        #pragma warning restore CS1591
        [EnumMember(Value = "photo.image_60x60")]
        #pragma warning disable CS1591
        PhotoImage60X60,
        #pragma warning restore CS1591
        [EnumMember(Value = "workspaces")]
        #pragma warning disable CS1591
        Workspaces,
        #pragma warning restore CS1591
        [EnumMember(Value = "workspaces.name")]
        #pragma warning disable CS1591
        WorkspacesName,
        #pragma warning restore CS1591
    }
}
