// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Asana.OpenApiClient.Models
{
    /// <summary>
    /// A map of the user&apos;s profile photo in various sizes, or null if no photo is set. Sizes provided are 21, 27, 36, 60, 128, and 1024. All images are in PNG format, except for 1024 (which is in JPEG format).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserBaseResponse_photo : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>JPEG image of the user at 1024x1024 pixels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image1024x1024 { get; set; }
#nullable restore
#else
        public string Image1024x1024 { get; set; }
#endif
        /// <summary>PNG image of the user at 128x128 pixels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image128x128 { get; set; }
#nullable restore
#else
        public string Image128x128 { get; set; }
#endif
        /// <summary>PNG image of the user at 21x21 pixels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image21x21 { get; set; }
#nullable restore
#else
        public string Image21x21 { get; set; }
#endif
        /// <summary>PNG image of the user at 27x27 pixels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image27x27 { get; set; }
#nullable restore
#else
        public string Image27x27 { get; set; }
#endif
        /// <summary>PNG image of the user at 36x36 pixels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image36x36 { get; set; }
#nullable restore
#else
        public string Image36x36 { get; set; }
#endif
        /// <summary>PNG image of the user at 60x60 pixels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image60x60 { get; set; }
#nullable restore
#else
        public string Image60x60 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Models.UserBaseResponse_photo"/> and sets the default values.
        /// </summary>
        public UserBaseResponse_photo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.UserBaseResponse_photo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Asana.OpenApiClient.Models.UserBaseResponse_photo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Asana.OpenApiClient.Models.UserBaseResponse_photo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "image_1024x1024", n => { Image1024x1024 = n.GetStringValue(); } },
                { "image_128x128", n => { Image128x128 = n.GetStringValue(); } },
                { "image_21x21", n => { Image21x21 = n.GetStringValue(); } },
                { "image_27x27", n => { Image27x27 = n.GetStringValue(); } },
                { "image_36x36", n => { Image36x36 = n.GetStringValue(); } },
                { "image_60x60", n => { Image60x60 = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("image_1024x1024", Image1024x1024);
            writer.WriteStringValue("image_128x128", Image128x128);
            writer.WriteStringValue("image_21x21", Image21x21);
            writer.WriteStringValue("image_27x27", Image27x27);
            writer.WriteStringValue("image_36x36", Image36x36);
            writer.WriteStringValue("image_60x60", Image60x60);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
