// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Asana.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Asana.OpenApiClient.Project_briefs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \project_briefs\{project_brief_gid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProject_brief_gItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProject_brief_gItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/project_briefs/{project_brief_gid}{?opt_fields}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProject_brief_gItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/project_briefs/{project_brief_gid}{?opt_fields}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes a specific, existing project brief.Returns an empty data record.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.EmptyResponseData"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.EmptyResponseData?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.EmptyResponseData> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Asana.OpenApiClient.Models.EmptyResponseData>(requestInfo, global::Soenneker.Asana.OpenApiClient.Models.EmptyResponseData.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the full record for a project brief.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.ProjectBriefResponseData"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 424 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 501 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.ProjectBriefResponseData?> GetAsync(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder.WithProject_brief_gItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.ProjectBriefResponseData> GetAsync(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder.WithProject_brief_gItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "424", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Asana.OpenApiClient.Models.ProjectBriefResponseData>(requestInfo, global::Soenneker.Asana.OpenApiClient.Models.ProjectBriefResponseData.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// An existing project brief can be updated by making a PUT request on the URL forthat project brief. Only the fields provided in the `data` block will be updated;any unspecified fields will remain unchanged.Returns the complete updated project brief record.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.ProjectBriefResponseData"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.ProjectBriefResponseData?> PutAsync(global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gPutRequestBody body, Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder.WithProject_brief_gItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.ProjectBriefResponseData> PutAsync(global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gPutRequestBody body, Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder.WithProject_brief_gItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Asana.OpenApiClient.Models.ProjectBriefResponseData>(requestInfo, global::Soenneker.Asana.OpenApiClient.Models.ProjectBriefResponseData.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes a specific, existing project brief.Returns an empty data record.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=UTF-8");
            return requestInfo;
        }
        /// <summary>
        /// Get the full record for a project brief.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder.WithProject_brief_gItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder.WithProject_brief_gItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=UTF-8");
            return requestInfo;
        }
        /// <summary>
        /// An existing project brief can be updated by making a PUT request on the URL forthat project brief. Only the fields provided in the `data` block will be updated;any unspecified fields will remain unchanged.Returns the complete updated project brief record.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gPutRequestBody body, Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder.WithProject_brief_gItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gPutRequestBody body, Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder.WithProject_brief_gItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=UTF-8");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json;charset=UTF-8", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithProject_brief_gItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Get the full record for a project brief.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithProject_brief_gItemRequestBuilderGetQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsGetOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.GetOpt_fieldsQueryParameterType[]? OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.GetOpt_fieldsQueryParameterType[] OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithProject_brief_gItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder.WithProject_brief_gItemRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// An existing project brief can be updated by making a PUT request on the URL forthat project brief. Only the fields provided in the `data` block will be updated;any unspecified fields will remain unchanged.Returns the complete updated project brief record.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithProject_brief_gItemRequestBuilderPutQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsPutOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.PutOpt_fieldsQueryParameterType[]? OptFieldsAsPutOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.PutOpt_fieldsQueryParameterType[] OptFieldsAsPutOptFieldsQueryParameterType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithProject_brief_gItemRequestBuilderPutRequestConfiguration : RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Project_briefs.Item.WithProject_brief_gItemRequestBuilder.WithProject_brief_gItemRequestBuilderPutQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
