// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Asana.OpenApiClient.Enum_options.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Asana.OpenApiClient.Enum_options
{
    /// <summary>
    /// Builds and executes requests for operations under \enum_options
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Enum_optionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Asana.OpenApiClient.enum_options.item collection</summary>
        /// <param name="position">Globally unique identifier for the enum option.</param>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Enum_options.Item.WithEnum_option_gItemRequestBuilder"/></returns>
        public global::Soenneker.Asana.OpenApiClient.Enum_options.Item.WithEnum_option_gItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("enum_option_gid", position);
                return new global::Soenneker.Asana.OpenApiClient.Enum_options.Item.WithEnum_option_gItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Enum_options.Enum_optionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Enum_optionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enum_options", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Enum_options.Enum_optionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Enum_optionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enum_options", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
