// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Workspaces.Item.Typeahead
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetResource_typeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "custom_field")]
        #pragma warning disable CS1591
        Custom_field,
        #pragma warning restore CS1591
        [EnumMember(Value = "goal")]
        #pragma warning disable CS1591
        Goal,
        #pragma warning restore CS1591
        [EnumMember(Value = "project")]
        #pragma warning disable CS1591
        Project,
        #pragma warning restore CS1591
        [EnumMember(Value = "project_template")]
        #pragma warning disable CS1591
        Project_template,
        #pragma warning restore CS1591
        [EnumMember(Value = "portfolio")]
        #pragma warning disable CS1591
        Portfolio,
        #pragma warning restore CS1591
        [EnumMember(Value = "tag")]
        #pragma warning disable CS1591
        Tag,
        #pragma warning restore CS1591
        [EnumMember(Value = "task")]
        #pragma warning disable CS1591
        Task,
        #pragma warning restore CS1591
        [EnumMember(Value = "team")]
        #pragma warning disable CS1591
        Team,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
    }
}
