// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Asana.OpenApiClient.Access_requests.Item.Approve;
using Soenneker.Asana.OpenApiClient.Access_requests.Item.Reject;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Asana.OpenApiClient.Access_requests.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \access_requests\{access_request_gid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAccess_request_gItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The approve property</summary>
        public global::Soenneker.Asana.OpenApiClient.Access_requests.Item.Approve.ApproveRequestBuilder Approve
        {
            get => new global::Soenneker.Asana.OpenApiClient.Access_requests.Item.Approve.ApproveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reject property</summary>
        public global::Soenneker.Asana.OpenApiClient.Access_requests.Item.Reject.RejectRequestBuilder Reject
        {
            get => new global::Soenneker.Asana.OpenApiClient.Access_requests.Item.Reject.RejectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Access_requests.Item.WithAccess_request_gItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccess_request_gItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/access_requests/{access_request_gid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Access_requests.Item.WithAccess_request_gItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccess_request_gItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/access_requests/{access_request_gid}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
