// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Workspaces.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PutOpt_fieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "email_domains")]
        #pragma warning disable CS1591
        Email_domains,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_organization")]
        #pragma warning disable CS1591
        Is_organization,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
    }
}
