// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Asana.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships
{
    /// <summary>
    /// Builds and executes requests for operations under \workspaces\{workspace_gid}\workspace_memberships
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Workspace_membershipsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Workspace_membershipsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces/{workspace_gid}/workspace_memberships{?limit*,offset*,opt_fields,user*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Workspace_membershipsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces/{workspace_gid}/workspace_memberships{?limit*,offset*,opt_fields,user*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the compact workspace membership records for the workspace.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.WorkspaceMembershipResponseArray"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.WorkspaceMembershipResponseArray?> GetAsync(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder.Workspace_membershipsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.WorkspaceMembershipResponseArray> GetAsync(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder.Workspace_membershipsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Asana.OpenApiClient.Models.WorkspaceMembershipResponseArray>(requestInfo, global::Soenneker.Asana.OpenApiClient.Models.WorkspaceMembershipResponseArray.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the compact workspace membership records for the workspace.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder.Workspace_membershipsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder.Workspace_membershipsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=UTF-8");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the compact workspace membership records for the workspace.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Workspace_membershipsRequestBuilderGetQueryParameters 
        {
            /// <summary>Results per page.The number of objects to return per page. The value must be between 1 and 100.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Offset token.An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results.*Note: You can only pass in an offset that was returned to you via a previously paginated request.*</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("offset")]
            public string? Offset { get; set; }
#nullable restore
#else
            [QueryParameter("offset")]
            public string Offset { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.GetOpt_fieldsQueryParameterType[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Workspace_memberships.GetOpt_fieldsQueryParameterType[] OptFields { get; set; }
#endif
            /// <summary>A string identifying a user. This can either be the string &quot;me&quot;, an email, or the gid of a user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("user")]
            public string? User { get; set; }
#nullable restore
#else
            [QueryParameter("user")]
            public string User { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
