// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Asana.OpenApiClient.Workspaces.Item.Tasks.Custom_id.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Asana.OpenApiClient.Workspaces.Item.Tasks.Custom_id
{
    /// <summary>
    /// Builds and executes requests for operations under \workspaces\{workspace_gid}\tasks\custom_id
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Custom_idRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Asana.OpenApiClient.workspaces.item.tasks.custom_id.item collection</summary>
        /// <param name="position">Generated custom ID for a task.</param>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Tasks.Custom_id.Item.WithCustom_ItemRequestBuilder"/></returns>
        public global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Tasks.Custom_id.Item.WithCustom_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("custom_id", position);
                return new global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Tasks.Custom_id.Item.WithCustom_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Tasks.Custom_id.Custom_idRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Custom_idRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces/{workspace_gid}/tasks/custom_id", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Workspaces.Item.Tasks.Custom_id.Custom_idRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Custom_idRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces/{workspace_gid}/tasks/custom_id", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
