// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Asana.OpenApiClient.Models;
using Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses
{
    /// <summary>
    /// Builds and executes requests for operations under \timesheet_approval_statuses
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Timesheet_approval_statusesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Asana.OpenApiClient.timesheet_approval_statuses.item collection</summary>
        /// <param name="position">Globally unique identifier for the timesheet approval status.</param>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Item.WithTimesheet_approval_status_gItemRequestBuilder"/></returns>
        public global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Item.WithTimesheet_approval_status_gItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("timesheet_approval_status_gid", position);
                return new global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Item.WithTimesheet_approval_status_gItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Timesheet_approval_statusesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/timesheet_approval_statuses?workspace={workspace}{&approval_statuses*,from_date*,limit*,offset*,opt_fields,to_date*,user*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Timesheet_approval_statusesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/timesheet_approval_statuses?workspace={workspace}{&approval_statuses*,from_date*,limit*,offset*,opt_fields,to_date*,user*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;timesheet_approval_statuses:read&lt;/code&gt;Returns a list of timesheet approval statuses filtered by workspace and optionally by user, date range, or approval status.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.TimesheetApprovalStatusResponseArray"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.TimesheetApprovalStatusResponseArray?> GetAsync(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder.Timesheet_approval_statusesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.TimesheetApprovalStatusResponseArray> GetAsync(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder.Timesheet_approval_statusesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Asana.OpenApiClient.Models.TimesheetApprovalStatusResponseArray>(requestInfo, global::Soenneker.Asana.OpenApiClient.Models.TimesheetApprovalStatusResponseArray.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;timesheet_approval_statuses:write&lt;/code&gt;Creates a new timesheet approval status for a user&apos;s timesheet week. The start_date must be a Monday and end_date must be the following Sunday.Returns the created timesheet approval status record.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Models.TimesheetApprovalStatusResponseData"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.TimesheetApprovalStatusResponseData?> PostAsync(global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder.Timesheet_approval_statusesRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Asana.OpenApiClient.Models.TimesheetApprovalStatusResponseData> PostAsync(global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder.Timesheet_approval_statusesRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Asana.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Asana.OpenApiClient.Models.TimesheetApprovalStatusResponseData>(requestInfo, global::Soenneker.Asana.OpenApiClient.Models.TimesheetApprovalStatusResponseData.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;timesheet_approval_statuses:read&lt;/code&gt;Returns a list of timesheet approval statuses filtered by workspace and optionally by user, date range, or approval status.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder.Timesheet_approval_statusesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder.Timesheet_approval_statusesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=UTF-8");
            return requestInfo;
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;timesheet_approval_statuses:write&lt;/code&gt;Creates a new timesheet approval status for a user&apos;s timesheet week. The start_date must be a Monday and end_date must be the following Sunday.Returns the created timesheet approval status record.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder.Timesheet_approval_statusesRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder.Timesheet_approval_statusesRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/timesheet_approval_statuses{?opt_fields}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=UTF-8");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json;charset=UTF-8", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.Timesheet_approval_statusesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;timesheet_approval_statuses:read&lt;/code&gt;Returns a list of timesheet approval statuses filtered by workspace and optionally by user, date range, or approval status.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Timesheet_approval_statusesRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by approval status. Can be one or more of draft, submitted, approved, or rejected.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("approval_statuses")]
            public string? ApprovalStatuses { get; set; }
#nullable restore
#else
            [QueryParameter("approval_statuses")]
            public string ApprovalStatuses { get; set; }
#endif
            /// <summary>The start date for filtering timesheet approval statuses.</summary>
            [QueryParameter("from_date")]
            public Date? FromDate { get; set; }
            /// <summary>Results per page.The number of objects to return per page. The value must be between 1 and 100.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Offset token.An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results.*Note: You can only pass in an offset that was returned to you via a previously paginated request.*</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("offset")]
            public string? Offset { get; set; }
#nullable restore
#else
            [QueryParameter("offset")]
            public string Offset { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.GetOpt_fieldsQueryParameterType[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.GetOpt_fieldsQueryParameterType[] OptFields { get; set; }
#endif
            /// <summary>The end date for filtering timesheet approval statuses.</summary>
            [QueryParameter("to_date")]
            public Date? ToDate { get; set; }
            /// <summary>Globally unique identifier for the user to filter timesheet approval statuses by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("user")]
            public string? User { get; set; }
#nullable restore
#else
            [QueryParameter("user")]
            public string User { get; set; }
#endif
            /// <summary>Globally unique identifier for the workspace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("workspace")]
            public string? Workspace { get; set; }
#nullable restore
#else
            [QueryParameter("workspace")]
            public string Workspace { get; set; }
#endif
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;timesheet_approval_statuses:write&lt;/code&gt;Creates a new timesheet approval status for a user&apos;s timesheet week. The start_date must be a Monday and end_date must be the following Sunday.Returns the created timesheet approval status record.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Timesheet_approval_statusesRequestBuilderPostQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.PostOpt_fieldsQueryParameterType[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Soenneker.Asana.OpenApiClient.Timesheet_approval_statuses.PostOpt_fieldsQueryParameterType[] OptFields { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
