// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Asana.OpenApiClient.Rule_triggers.Item.Run;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Asana.OpenApiClient.Rule_triggers.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \rule_triggers\{rule_trigger_gid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRule_trigger_gItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The run property</summary>
        public global::Soenneker.Asana.OpenApiClient.Rule_triggers.Item.Run.RunRequestBuilder Run
        {
            get => new global::Soenneker.Asana.OpenApiClient.Rule_triggers.Item.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Rule_triggers.Item.WithRule_trigger_gItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRule_trigger_gItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rule_triggers/{rule_trigger_gid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Asana.OpenApiClient.Rule_triggers.Item.WithRule_trigger_gItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRule_trigger_gItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rule_triggers/{rule_trigger_gid}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
