// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Allocations
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOpt_fieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "assignee")]
        #pragma warning disable CS1591
        Assignee,
        #pragma warning restore CS1591
        [EnumMember(Value = "assignee.name")]
        #pragma warning disable CS1591
        AssigneeName,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_by")]
        #pragma warning disable CS1591
        Created_by,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_by.name")]
        #pragma warning disable CS1591
        Created_byName,
        #pragma warning restore CS1591
        [EnumMember(Value = "effort")]
        #pragma warning disable CS1591
        Effort,
        #pragma warning restore CS1591
        [EnumMember(Value = "effort.type")]
        #pragma warning disable CS1591
        EffortType,
        #pragma warning restore CS1591
        [EnumMember(Value = "effort.value")]
        #pragma warning disable CS1591
        EffortValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_date")]
        #pragma warning disable CS1591
        End_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "offset")]
        #pragma warning disable CS1591
        Offset,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent")]
        #pragma warning disable CS1591
        Parent,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent.name")]
        #pragma warning disable CS1591
        ParentName,
        #pragma warning restore CS1591
        [EnumMember(Value = "path")]
        #pragma warning disable CS1591
        Path,
        #pragma warning restore CS1591
        [EnumMember(Value = "resource_subtype")]
        #pragma warning disable CS1591
        Resource_subtype,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_date")]
        #pragma warning disable CS1591
        Start_date,
        #pragma warning restore CS1591
        [EnumMember(Value = "uri")]
        #pragma warning disable CS1591
        Uri,
        #pragma warning restore CS1591
    }
}
