// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Asana.OpenApiClient.Project_memberships.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOpt_fieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "access_level")]
        #pragma warning disable CS1591
        Access_level,
        #pragma warning restore CS1591
        [EnumMember(Value = "member")]
        #pragma warning disable CS1591
        Member,
        #pragma warning restore CS1591
        [EnumMember(Value = "member.name")]
        #pragma warning disable CS1591
        MemberName,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent")]
        #pragma warning disable CS1591
        Parent,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent.name")]
        #pragma warning disable CS1591
        ParentName,
        #pragma warning restore CS1591
        [EnumMember(Value = "project")]
        #pragma warning disable CS1591
        Project,
        #pragma warning restore CS1591
        [EnumMember(Value = "project.name")]
        #pragma warning disable CS1591
        ProjectName,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "user.name")]
        #pragma warning disable CS1591
        UserName,
        #pragma warning restore CS1591
        [EnumMember(Value = "write_access")]
        #pragma warning disable CS1591
        Write_access,
        #pragma warning restore CS1591
    }
}
